name: Build and publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish web and bundle with Gradle
        if: ${{ !contains(github.event.head_commit.message, 'no bundle') }}
        run: ./gradlew publish buildWeb --no-daemon
        env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
      - name: Publish web with Gradle
        if: ${{ contains(github.event.head_commit.message, 'no bundle') }}
        run: ./gradlew buildWeb --no-daemon
        env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/takenaka/web
          single-commit: true
          commit-message: 'build: update with ${{ github.sha }}'
